import type { Book } from "./types";

export const BOOKS: Book[] = [
  {
    title: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Science Fiction",
    year: 2021,
    pages: 496,
    isRead: true,
  },
  {
    title: "The Martian",
    author: "Andy Weir",
    genre: "Science Fiction",
    year: 2011,
    pages: 369,
    isRead: false,
  },
  {
    title: "The Metamorphosis",
    author: "Franz Kafka",
    genre: "Classic / Existential",
    year: 1915,
    pages: 128,
    isRead: false,
  },
  {
    title: "The Trial",
    author: "Franz Kafka",
    genre: "Classic / Existential",
    year: 1925,
    pages: 255,
    isRead: false,
  },
  {
    title: "Nineteen Eighty-Four",
    author: "George Orwell",
    genre: "Dystopian",
    year: 1949,
    pages: 328,
    isRead: false,
  },
  {
    title: "Animal Farm",
    author: "George Orwell",
    genre: "Political Satire",
    year: 1945,
    pages: 112,
    isRead: true,
  },
  {
    title: "Mistborn: The Final Empire",
    author: "Brandon Sanderson",
    genre: "Fantasy",
    year: 2006,
    pages: 541,
    isRead: false,
  },
  {
    title: "The Well of Ascension",
    author: "Brandon Sanderson",
    genre: "Fantasy",
    year: 2007,
    pages: 590,
    isRead: false,
  },
  {
    title: "The Hero of Ages",
    author: "Brandon Sanderson",
    genre: "Fantasy",
    year: 2008,
    pages: 572,
    isRead: false,
  },
  {
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    genre: "Epic Fantasy",
    year: 2010,
    pages: 1007,
    isRead: false,
  },
  {
    title: "Words of Radiance",
    author: "Brandon Sanderson",
    genre: "Epic Fantasy",
    year: 2014,
    pages: 1087,
    isRead: false,
  },
  {
    title: "Ficciones",
    author: "Jorge Luis Borges",
    genre: "Classic / Short Stories",
    year: 1944,
    pages: 224,
    isRead: true,
  },
  {
    title: "The Aleph",
    author: "Jorge Luis Borges",
    genre: "Classic / Short Stories",
    year: 1949,
    pages: 160,
    isRead: true,
  },
  {
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    genre: "Magical Realism",
    year: 1967,
    pages: 417,
    isRead: true,
  },
  {
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    genre: "Fantasy",
    year: 2007,
    pages: 662,
    isRead: false,
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    genre: "Science Fiction",
    year: 1965,
    pages: 412,
    isRead: true,
  },
  {
    title: "Do Androids Dream of Electric Sheep?",
    author: "Philip K. Dick",
    genre: "Science Fiction",
    year: 1968,
    pages: 210,
    isRead: true,
  },
  {
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    genre: "Science Fiction",
    year: 1969,
    pages: 304,
    isRead: true,
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    year: 1932,
    pages: 311,
    isRead: true,
  },
  {
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    genre: "Classic / Philosophical",
    year: 1880,
    pages: 824,
    isRead: true,
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    genre: "Classic / Psychological",
    year: 1866,
    pages: 671,
    isRead: true,
  },
  {
    title: "The Stranger",
    author: "Albert Camus",
    genre: "Classic / Existential",
    year: 1942,
    pages: 123,
    isRead: true,
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    genre: "Classic / Gothic",
    year: 1890,
    pages: 254,
    isRead: true,
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    genre: "Classic / Gothic",
    year: 1818,
    pages: 280,
    isRead: true,
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    genre: "Classic / Gothic",
    year: 1897,
    pages: 418,
    isRead: true,
  },
];
